FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Expose the port the app runs in
EXPOSE 3001

# Environmental Variables
#ENV DB_HOST=localhost
#ENV DB_PORT=27017
#ENV DB_NAME=snakeGame
#ENV DB_USER=
#ENV DB_PASS=

# Run the app
CMD [ "node", "index.js" ]
